name: Hashnode Blogs
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: latest blogs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "HASHNODE"
          commit_message: "Added latest blogs from the RSS"
          feed_list: "https://operationsguy.hashnode.dev/rss.xml"


